# Generated by Django 3.1.7 on 2021-03-05 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('apply', '0001_initial'),
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='posting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posting.posting'),
        ),
        migrations.AddField(
            model_name='apply',
            name='process_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.processstatus'),
        ),
        migrations.AddField(
            model_name='apply',
            name='reward_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.rewardstatus'),
        ),
        migrations.AddField(
            model_name='apply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
