# Generated by Django 3.1.7 on 2021-03-10 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20210305_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='process_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apply.processstatus'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='reward_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apply.rewardstatus'),
        ),
    ]
