# Generated by Django 3.1.7 on 2021-03-05 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='posting_like',
            field=models.ManyToManyField(related_name='user_like_posting', through='posting.Like', to='user.User'),
        ),
        migrations.AddField(
            model_name='posting',
            name='posting_mark',
            field=models.ManyToManyField(related_name='user_mark_posting', through='posting.BookMark', to='user.User'),
        ),
        migrations.AddField(
            model_name='like',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.posting'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.occupation'),
        ),
        migrations.AddField(
            model_name='companytag',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.company'),
        ),
        migrations.AddField(
            model_name='companytag',
            name='tag_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.tagdetail'),
        ),
        migrations.AddField(
            model_name='companyimage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.company'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.company'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.county'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.state'),
        ),
        migrations.AddField(
            model_name='company',
            name='tag',
            field=models.ManyToManyField(through='posting.CompanyTag', to='posting.TagDetail'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.posting'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
