# Generated by Django 3.1.7 on 2021-03-07 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('posting', '0002_auto_20210305_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='work_experience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.workexperience'),
            preserve_default=False,
        ),
    ]
