# Generated by Django 3.1.7 on 2021-03-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20210303_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='description',
            field=models.TextField(),
        ),
    ]
