# Generated by Django 3.1.7 on 2021-03-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210304_1547'),
        ('posting', '0003_auto_20210304_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='posting_like',
            field=models.ManyToManyField(related_name='user_like_posting', through='posting.Like', to='user.User'),
        ),
        migrations.AddField(
            model_name='posting',
            name='posting_mark',
            field=models.ManyToManyField(related_name='user_mark_posting', through='posting.BookMark', to='user.User'),
        ),
    ]
