# Generated by Django 3.1.7 on 2021-03-07 13:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'resume_statuses',
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2021, 3, 7, 13, 29, 37, 617537)),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='update_at',
            field=models.DateField(default=datetime.datetime(2021, 3, 7, 13, 29, 37, 617558)),
        ),
        migrations.AlterField(
            model_name='career',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='language',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='resume',
            name='complete_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.resumestatus'),
        ),
    ]
