# Generated by Django 3.1.7 on 2021-03-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210304_1547'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResumeDefault',
            new_name='Resume',
        ),
        migrations.RenameModel(
            old_name='ResumeSelf',
            new_name='ResumeFile',
        ),
        migrations.AlterModelTable(
            name='resume',
            table='resumes',
        ),
        migrations.AlterModelTable(
            name='resumefile',
            table='resume_files',
        ),
    ]
