# Generated by Django 3.1.7 on 2021-03-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210307_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
