# Generated by Django 3.1.7 on 2021-03-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20210307_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumefile',
            name='create_at',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumefile',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]