# Generated by Django 3.1.7 on 2021-03-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20210307_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumefile',
            name='uuidcode',
            field=models.CharField(default='default', max_length=3000),
            preserve_default=False,
        ),
    ]
