# Generated by Django 3.1.7 on 2021-03-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20210310_1019'),
        ('resume', '0004_auto_20210310_0403'),
    ]

    operations = [
    ]
