# Generated by Django 3.1.7 on 2021-03-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_merge_20210310_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumefile',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
